default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'app_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'app_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'app_production' %>
