version: '2'
services:
  db:
    image: postgres:9.6.1
    ports:
      - '5432:5432'

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    environment:
      - DB_HOST='db'
      - DB_USERNAME='postgres'
      - DB_PASSWORD=''
    ports:
      - '3000:3000'
    links:
      - db
    volumes:
      - .:/app
