---
- hosts: all
  user: vagrant

  roles:
    - role: utils
    - role: rvm_io.ruby
      rvm1_rubies: ["ruby-2.4.0"]
      rvm1_user: vagrant
    - role: nodejs
    - role: postgresql
    - role: sample-app
    - role: heroku-toolbelt
