---
  - name: install useful packages
    become: true
    apt:
      pkg: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - git
      - mc
      - vim
      - tmux

  - name: set default editor
    become: true
    alternatives:
      name: editor
      path: /usr/bin/vim.basic
